#define EXPORT_CARGO 1
#define EXPORT_EMAG 2
#define EXPORT_CONTRABAND 4
#define EXPORT_PIRATE 8

#define MARKET_CATEGORY_MATERIALS "materials"

#define BOUNTY_CATEGORY_SUPPLY "supply" //miners mostly
#define BOUNTY_CATEGORY_TEST "guh"

#define BOUNTY_STATUS_AVAILABLE 1
#define BOUNTY_STATUS_ACTIVE 2
#define BOUNTY_STATUS_COMPLETED 3
#define BOUNTY_STATUS_FAILED 4
