#define EXPORT_CARGO 1
#define EXPORT_EMAG 2
#define EXPORT_CONTRABAND 4
#define EXPORT_PIRATE 8

#define MARKET_CATEGORY_MINING "mining"
#define MARKET_CATEGORY_SECURITY "security"
#define MARKET_CATEGORY_ENGINEERING "engineering"
#define MARKET_CATEGORY_SCIENCE "science"
#define MARKET_CATEGORY_MEDICAL "medical"
#define MARKET_CATEGORY_SERVICE "service"
#define MARKET_CATEGORY_MISC "misc"

#define BOUNTY_CATEGORY_SUPPLY "supply" //miners mostly
#define BOUNTY_CATEGORY_TEST "guh"

#define BOUNTY_STATUS_AVAILABLE 1
#define BOUNTY_STATUS_ACTIVE 2
#define BOUNTY_STATUS_COMPLETED 3
#define BOUNTY_STATUS_FAILED 4
